language: java
jdk:
  - openjdk11
script:
  - mvn clean install
before_install:
  - chmod +x mvnw
  - chmod +x docker_push
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
